version: '2.2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - web-root:/var/www/html
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:15.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_BASE: project_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./db/shortcut/data2:/var/lib/postgresql/data2
    networks:
      - app-network
  app:
    container_name: kr_controller_master
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=project_db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "SERVER_PORT=8080"
    expose:
      - "8080"
    depends_on:
      - nginx
      - db
    restart: no
    networks:
      - app-network

volumes:
  web-root:

networks:
  app-network:
    driver: bridge