version: '2.2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - web-root:/var/www/html
    networks:
      - app-network

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    networks:
      - app-network

  db2:
    container_name: db2
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kr_db
    ports:
      - "5433:5433"
    restart: always
    volumes:
      - ./db/shortcut/data3:/var/lib/postgresql/data
    networks:
      - app-network

  app_db:
      container_name: app_db
      image: kr_db
      networks:
        - app-network

  app:
    container_name: kr_controller_master
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=project_db"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "SERVER_PORT=8080"
    expose:
      - "8080"
    ports:
      - "8081:8080"
    depends_on:
      - nginx
      - db
    restart: always
    networks:
      - app-network

volumes:
  web-root:

networks:
  app-network:
    driver: bridge